name: dart_modbus_workspace
description: Dart Modbus monorepo workspace
version: 1.0.0
publish_to: none  # Workspace root is not published

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
  melos: ^6.3.2

# Cider configuration for CHANGELOG management
# See: doc/CHANGELOG_GUIDE.md
cider:
  link_template:
    tag: "https://github.com/yourname/dart-modbus/releases/tag/%tag%"
    diff: "https://github.com/yourname/dart-modbus/compare/%from%...%to%"